/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtisanAppRouteImport } from './routes/artisan-app'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FairsRouteImport } from './routes/fairs'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PostRouteImport } from './routes/post'
import { Route as RequirementRouteImport } from './routes/requirement'
import { Route as ArtisansArtisanIdRouteImport } from './routes/artisans.$artisanId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanAppRoute = ArtisanAppRouteImport.update({
  id: '/artisan-app',
  path: '/artisan-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FairsRoute = FairsRouteImport.update({
  id: '/fairs',
  path: '/fairs',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementRoute = RequirementRouteImport.update({
  id: '/requirement',
  path: '/requirement',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansArtisanIdRoute = ArtisansArtisanIdRouteImport.update({
  id: '/artisans/$artisanId',
  path: '/artisans/$artisanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artisan-app': typeof ArtisanAppRoute
  '/discover': typeof DiscoverRoute
  '/fairs': typeof FairsRoute
  '/orders': typeof OrdersRoute
  '/post': typeof PostRoute
  '/requirement': typeof RequirementRoute
  '/artisans/$artisanId': typeof ArtisansArtisanIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artisan-app': typeof ArtisanAppRoute
  '/discover': typeof DiscoverRoute
  '/fairs': typeof FairsRoute
  '/orders': typeof OrdersRoute
  '/post': typeof PostRoute
  '/requirement': typeof RequirementRoute
  '/artisans/$artisanId': typeof ArtisansArtisanIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artisan-app': typeof ArtisanAppRoute
  '/discover': typeof DiscoverRoute
  '/fairs': typeof FairsRoute
  '/orders': typeof OrdersRoute
  '/post': typeof PostRoute
  '/requirement': typeof RequirementRoute
  '/artisans/$artisanId': typeof ArtisansArtisanIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artisan-app'
    | '/discover'
    | '/fairs'
    | '/orders'
    | '/post'
    | '/requirement'
    | '/artisans/$artisanId'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artisan-app'
    | '/discover'
    | '/fairs'
    | '/orders'
    | '/post'
    | '/requirement'
    | '/artisans/$artisanId'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/artisan-app'
    | '/discover'
    | '/fairs'
    | '/orders'
    | '/post'
    | '/requirement'
    | '/artisans/$artisanId'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtisanAppRoute: typeof ArtisanAppRoute
  DiscoverRoute: typeof DiscoverRoute
  FairsRoute: typeof FairsRoute
  OrdersRoute: typeof OrdersRoute
  PostRoute: typeof PostRoute
  RequirementRoute: typeof RequirementRoute
  ArtisansArtisanIdRoute: typeof ArtisansArtisanIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan-app': {
      id: '/artisan-app'
      path: '/artisan-app'
      fullPath: '/artisan-app'
      preLoaderRoute: typeof ArtisanAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairs': {
      id: '/fairs'
      path: '/fairs'
      fullPath: '/fairs'
      preLoaderRoute: typeof FairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirement': {
      id: '/requirement'
      path: '/requirement'
      fullPath: '/requirement'
      preLoaderRoute: typeof RequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans/$artisanId': {
      id: '/artisans/$artisanId'
      path: '/artisans/$artisanId'
      fullPath: '/artisans/$artisanId'
      preLoaderRoute: typeof ArtisansArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtisanAppRoute: ArtisanAppRoute,
  DiscoverRoute: DiscoverRoute,
  FairsRoute: FairsRoute,
  OrdersRoute: OrdersRoute,
  PostRoute: PostRoute,
  RequirementRoute: RequirementRoute,
  ArtisansArtisanIdRoute: ArtisansArtisanIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
